version: '3.8'

services:
  warp2api:
    build: .
    container_name: warp2api
    ports:
      - "3009:8000"  # Protobuf 编解码服务器端口
      - "3010:8010"  # OpenAI 兼容 API 服务器端口
    environment:
      - HOST=0.0.0.0
      - PORT=8010
      - WARP_BRIDGE_URL=http://127.0.0.1:8000
      - WARP_LOG_LEVEL=info
      - WARP_ACCESS_LOG=true
      - OPENAI_LOG_LEVEL=info
      - OPENAI_ACCESS_LOG=true
      # 可选：如果有自己的 Warp 凭证，可以取消注释并填写
      # - WARP_JWT=your_jwt_token_here
      # - WARP_REFRESH_TOKEN=your_refresh_token_here
    volumes:
      # 可选：挂载日志目录
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8010/healthz", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  default:
    name: warp2api_network
